### ISSUE TITLE
i want ask mfs can support the minio's file objects permissions control  scene

### ISSUE THREAD

**Issue by belugaliu** [minio/mfs#1]
hi,i see some mfs's go files, i see you use sso and credentials to control user access. but will mfs control the minio's file object may can't be accessed although the user can pass sso's validation?
i means  will mfs support controll some special file objects's access permission only open to some tenantrys not all tenantrys who can pass sso's validation?

**Comment by harshavardhana** [comment]
mfs is work in progress project. The plans are to support SSO.

**Comment by belugaliu** [comment]
ok, thanks. it means if want support the scene, i need do it in my project.

**Comment by harshavardhana** [comment]
> ok, thanks. it means if want support the scene, i need do it in my project.

Yes that is correct currently you have to do it in your project.  Closing this issue as answered, this repo is not ready to used yet.
